### ISSUE TITLE
Indentation is not respected in `json-mode`

### ISSUE THREAD

**Issue by hjpotter92** [jcs-elpa/indent-control#1]
I have the following configuration for `indent-control` package:

``` elisp

(use-package indent-control
  :init
  (setq indent-control-records
        '((actionscript-mode     . 4)
          .
          .
          .
          (groovy-mode           . 4)
          (java-mode             . 4)
	  (javascript-mode       . 2)
          (jayces-mode           . 4)
          (js-mode               . 2)
          (js2-mode              . 2)
          (js3-mode              . 2)
          (json-mode             . 2)
          .
          .
          .
          (typescript-mode       . 4)
          (web-mode              . 2)
          (yaml-mode             . 2)))
  :config
  (indent-control-mode t))
```

I open a new json file (`C-x C-f ~/test.json`) and type in the following:

```json
{
    "test": "something"
}
```

The indentation for the line-2 is always going to 4 spaces, whereas in the records I've specified the same to be 2 `json-mode/javascript-mode/js[23]-mode`.

I tried reproducing the behaviour in a clean emacs setup (`docker run ubuntu bash`, install `emacs-nox` and proceed), and the same behaviour was observed there. The active modes at the time (for json file):

```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Electric-Indent File-Name-Shadow Font-Lock Global-Eldoc
Global-Font-Lock Indent-Control Line-Number Menu-Bar Tooltip
Transient-Mark

(Information about these minor modes follows the major mode info.)

JSON mode defined in `json-mode.el':
Major mode for editing JSON files

In addition to any hooks its parent mode `javascript-mode' might have run,
this mode runs the hook `json-mode-hook', as the final or penultimate step
during initialization.
```

Any hints/ideas as to what might be wrong?

**Comment by jcs090218** [comment]
Thanks for reporting this issue. I think I overlooked the `json-mode`'s indentation level variable. I think commit 383ea506a6e6145bbb6327a7b1e509b40edf446b should resolve this issue. For quick fix; try adding `(json-mode . js-indent-level)` to `indent-control-alist`.

Hope this helps. :)
