### ISSUE TITLE
Indent offset values missing for sh-script.el

### ISSUE THREAD

**Issue by hjpotter92** [jcs-elpa/indent-control#2]
I was updating a shell script, and kept getting the warning

> smie-indent-line: Wrong type argument: number-or-marker-p, nil

which is due to missing `sh-basic-offset` parameter configuration in the package.

**Comment by jcs090218** [comment]
I think the variable `indent-control-alist` is missing `(sh-mode . sh-basic-offset)`? Would you like to make a PR for this? And maybe apply it to the variable `indent-control-records` too.

**Comment by hjpotter92** [comment]
> I think the variable `indent-control-alist` is missing `(sh-mode . sh-basic-offset)`? Would you like to make a PR for this? And maybe apply it to the variable `indent-control-records` too. Thanks!

done. :)
